### ISSUE TITLE
RL-1: SMARTS for ionization centers

### ISSUE THREAD

**Issue by Ruibin-Liu** [Global-Chem/global-chem#38]
Check out this page for the SMARTS patterns for all ionization centers for small molecules (maybe same for residues?)
https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fxundrug.cn%2Fdata%2FSMARTS_Ionizable_groups.docx&wdOrigin=BROWSELINK

**Comment by Ruibin-Liu** [comment]
Also, it'll be good to have the 'atom_id of Ionization center' and 'acid_or_base' flags for the function returns.

**Comment by Ruibin-Liu** [comment]
You can add to the miscellaneous node.

**Comment by Sulstice** [comment]
Hmmm, can you explain the ionization center component? Also do you have a reference for this list? I think this is good too, There is some api architecture I can implement as well to get more refined functionality.

**Comment by Sulstice** [comment]
I would need to name all of these as well, what is your suggestion for an IUPAC name for one of these compounds?

**Comment by Sulstice** [comment]
So let's stall the list, and maybe you can add that one yourself, but I think I have a good idea of what you need now:

Let's save this here for reference sake:

```

'[#6+0!$(*~[#7,#8,F]),SH0+0v2,s+0,S^3,Cl+0,Br+0,I+0]',
                '[a]',
                '[!$([#1,#6,F,Cl,Br,I,o,s,nX3,#7v5,#15v5,#16v4,#16v6,*+1,*+2,*+3])]',
                '[!$([#6,H0,-,-2,-3]),$([!H0;#7,#8,#9])]',
                '[r]'
]= ['hydrophobic', 'aromatic', 'acceptor', 'donor',
                             'ring']
```

**Comment by j-wags** [comment]
Sorry for the drive-by comment, but I wonder if having multiple "tagged atoms" in each [ionizable group definition](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fxundrug.cn%2Fdata%2FSMARTS_Ionizable_groups.docx&wdOrigin=BROWSELINK) is necessary (or if I'm missing context)? 

For example the first entry includes seven atoms, six of which are tagged (all except the final `[H]`):

|    | SMARTS|  Atom_id of Ionization center | Acid _or_ base |
|---|---|---|---|
|1 | `[SX4:1](=[O:2])(=[O:3])([O:4]-[C,c,N,n:5])-[OX2:6]-[H]` | 6 | A |

Could this instead be written more compactly as?

`[SX4](=[O])(=[O])([O]-[C,c,N,n])-[OX2:1]-[H]`

Where the ionizable center is always tagged as atom 1? If it's necessary to mark which H is leaving, that could always be marked with `:2` (for acids). 

Also, I noticed that further down in the list are several SMILES with no atom tags (`[#:X]`), but which still have an atom id for the ionizable center. I've caused myself several headaches by relying on an atom order defined by "reading a SMILES from left to right", and I'd strongly recommend avoiding that when possible! Cheminformatics toolkits are free to read SMILES without any guarantees about reading from left-to-right or write molecules to SMILES without maintaining any specific atom ordering.

**Comment by Sulstice** [comment]
Hey @j-wags, so we also discussed this feature a bit in-person at school so there might be some discussion gap, I'll fill it in.

We are thinking of moving proteins into `SMARTS` strings and marking the classes of a amino acid peptide sequence with ionizable centers as well as small molecules and developing the feature with respect to both. 

So yeah you are right, they flood the string with `atom` classes and then highlight which one is the ionizable center. And yeah this where you could specify the based on the atom class if it's "base" or "acid" i.e `[:1]` and `[:2]` respectively. 

Interesting `[#:X]` meaning an atom with a class of `X` so perhaps this atom might have a dummy position to account for in their code - marking a site point for a reason.

With the following string:

 ```

[SX4:1](=[O:2])(=[O:3])([O:4]-[C,c,N,n:5])-[OX2:6]-[H]

```

I actually like this output they constructed. I often work on building CGenFF, and I can map the atom classes to different atom types based on our language engine so in the future as a forcefield developer that would be interesting to me to capture this scenario within our context. I'll reduce the classes down at a later level perhaps if the same atom type is repeated twice so I know they know belong to one class. 

Yeah rank ordering of `SMILES` can be tricky.  I do often check for preservation since jumping between software you never know. 

Let me write a first pass implementation to get a feel for how it looks - won't take long but I'll be in class for the next 6-8 hours so deep into the evening. 

**Edit** Reading over my comment, they probably marked :X as dummy atom classes  to mimic the electron placement. I think, will need to read the paper.

**Comment by Ruibin-Liu** [comment]
Hi @xiaolinpan, we are trying to add your list of SMARTS for ionization centers to global-chem's Chemistry <--> Cheminformatics language lib. How do you think of @j-wags 's comment about the multiple tags and other issues?

**Comment by xiaolinpan** [comment]
Sorry for not providing clear notes, the atom_id is just the index of the substructure match results by RDKit or openbabel. The index number in the SMARTS string is not necessary.

**Comment by Sulstice** [comment]
Thanks for clarifying, I know what to do. Give me a couple of days. I had this idea a couple of years ago too now that I remember, just never implemented. MOE implemented this in their software and one other I think, Durrant's Lab.  

Interview Day for applicants, I'll tackle it this weekend.

**Comment by Sulstice** [comment]
@Ruibin-Liu 

So in regards to protonation states do this now:

```

from global_chem_extensions.global_chem_extensions import GlobalChemExtensions

amino_acid_test = ['RSTEFGHIKLADPQ']
smiles = GlobalChemExtensions().amino_acids_to_smiles(amino_acid_test)
print (smiles)
GlobalChemExtensions().find_protonation_states(
    smiles,
    min_ph=4.0,
    max_ph=8.1,
    pka_precision=1.0,
    max_variants=128,
    label_states=False,
)

```

Fair warning Data Explosion

<img width="1086" alt="Screen Shot 2022-03-13 at 5 34 39 PM" src="https://user-images.githubusercontent.com/11812946/158080609-385f1c5d-c67c-47ba-8897-b5cb4feae109.png">

If we start off with amino acid sequence from proteins and convert to SMILES using my algorithm it should be efficient for collectiing all protonation states of both small molecules and proteins over a range of pH. Also I like this better since it keeps it within 1-D. 

We can easily get 3-D coordinates using my other algo under the hood. This will evaluate the range of the pH so we can mimic the cpHMD conditions. 

8d9ea77e3227b3de0998f00d2753e921662187ce

**Comment by Sulstice** [comment]
I had to go back to my youth @Ruibin-Liu 

This is done:

Use biopandas for pdb processing. I trust the author of that software. 

```
gc_protein = gce.initialize_globalchem_protein(
        # pdb_file='file.pdb',
        # fetch_pdb='5tc0',
        peptide_sequence='AAAA',
)

smiles_protein = gc_protein.convert_to_smiles(
    mark_nitrogen_backbone=True,
    mark_carbonyl_carbon_backbone = False,
)
print (smiles_protein)

smarts_protein = gc_protein.convert_to_smarts(
    mark_nitrogen_backbone=True,
    mark_carbonyl_carbon_backbone = False,
)
print (smarts_protein)
```

Output:

```

[N:1]C(C)C([N:1]C(C)C([N:1]C(C)C([N:1]C(C)C([N:1]CC(O)=O)=O)=O)=O)=O
[#7:1]-[#6](-[#6])-[#6](-[#7:1]-[#6](-[#6])-[#6](-[#7:1]-[#6](-[#6])-[#6](-[#7:1]-[#6](-[#6])-[#6](-[#7:1]-[#6]-[#6](-[#8])=[#8])=[#8])=[#8])=[#8])=[#8]

```

All docs are updated. Anymore ionization centers we can isolate myself and follow my pattern. Use mine and not anyone elses. 

Thanks for being patient ruibin.

**Comment by Sulstice** [comment]
ba8acb9cb6237b3f9ab7f9219c838162ca54a7ec
